-   id: echo-entrypoint
    name: echo (via --entrypoint)
    language: docker_image
    entry: --entrypoint echo alpine:3.10.1
-   id: echo-cmd
    name: echo (via cmd)
    language: docker_image
    entry: alpine:3.10.1 echo
